<!doctype html>
<html class="no-js" lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Foundation Starter Template</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.1/foundation.min.css" />

  <style type="text/css">
    .center{
      text-align: center; 
      color:white;
    }

    .color_box{
      background-color: rgba(33, 153, 232, 0.34);
    }
    .center_box{
      position:relative;
      top:40%;
    }

    body{
      background-image:url('http://www.themesltd.com/backgrounds/random/pixel_shooting_stars_in_space.gif');
    }

  </style>
</head>
<body>
  <header>

  </header>

  <main class="row center_box">
    <div class="medium-12 columns">
      <div class="row">
        <div class="medium-6 medium-centered columns color_box">
          <h1 class="center">Short your URL</h1>
          <div class="row">
          <div class="medium-12 medium-centered columns">
              <form>
                <div class="row">
                  <div class="medium-9 columns">
                    <input type="text" placeholder="exemplo.com.br" />
                  </div> 

                  <div class="medium-3 columns">
                    <button class="button">Short it!</button>
                  </div> 
                </div>
              </form>
            </div>
          </div>
          <p class="center"> Todos os direitos não reservados, 2016</p>
        </div>
      </div>
    </div>
  </main>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.1/foundation.min.js"></script>
  <script>
    $(document).foundation();
  </script>
</body>
</html>